$(".headerpage").load('./html/header.html')
$('.shoopingCart').load('./html/shoppingCart.html')
$('.SigninSignup').load('./html/SigninSignup.html')
$('.ChatBox').load('./html/ChatBox.html')
$('.footerpage').load('./html/footer.html')